sudo: true
language: php
dist: trusty
php:
  - '7.2'

services:
  - mysql

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - mkdir build

install:
  - composer install

script:
  - composer test